debug: true
server:
    port: 8080
logging:
  level:
    logging.level.org.springframework.security: TRACE
app:
    service-principal: HTTP/spring-security-sso-kerberos
    keytab-location: file://${user.home}/spring-security-sso-kerberos.keytab

