debug: true
server:
    port: 8080
logging:
  level:
    logging.level.org.springframework.security: TRACE
app:
    service-principal: HTTP/neo.example.org@EXAMPLE.ORG
    keytab-location: /tmp/tomcat.keytab
